[package]
name = "aoc_2018"
version = "0.1.0"
authors = ["Gerard Klijs <g.klijs@gmail.com>"]
edition = "2018"

[dependencies]
aoc-runner = "0.2.0"
aoc-runner-derive = "0.2.0"
regex = "1.1.0"
lazy_static = "1.2.0"